### ISSUE TITLE
Update react native version to the latest version

### ISSUE THREAD

**Issue by yasharAyari** [LiskHQ/lisk-mobile#1003]
### Description of the problem
The current version of lisk-mobile uses version 0.59.x of react-native. by updating to the latest version(0.61.x) we will achieve better performance and support, especially on Android devices.

### Suggested solution
Upgrade to the latest version of react-native.

**Task list**

- [x] Updating react-native to latest version . 
- [x] Update libraries that broke with react-native 0.61.3
- [x] Fix Android build
- [ ] Fix ios build
- [ ] Test manually everything in different devices 
- [ ] Update libraries that might needed to be updated based on previous step
- [ ] Test again
- [ ] Fix automatic tests

**Comment by RaquelCasadoDias** [comment]
Issue's progress:
[x] Updating react-native to latest version . 
[x] Update libraries that broke with react-native 0.61.3
[x] Fix Android build
[ ] Fix ios build
[ ] Test manually everything in different devices 
[ ] Update libraries that might needed to be updated based on previous step
[ ] Test again
[ ] Fix automatic tests
