### ISSUE TITLE
Refactor the validators of Send steps

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-mobile#587]
We need to refactor our utility set in order to cover the differences between BTC and LSK.

LSK has a static fee but BTC offers dynamic fees. this means that in Send page we should revalidate the input after the user changed the fee value. This requires a properly designed UI to reflect the effect of the fee on validation.

BTC doesn't offer reference field, this step should not be present when transferring BTC.

---

- [x] Recipient step - LSK / BTC address [#661]
- [x] Add to Bookmarks Step - Label [#665]  
- [x] Amount - Dynamic fee logic for BTC [#669]
- [x] Second Passphrase [#670]
- [x] Reference - Bytes [#667]
- [x] Overview - Error callback of transactionAdded action [#671]
